### ISSUE TITLE
Bug: Stream#update_value always uses v1 timestamp field name.

### ISSUE THREAD

**Issue by jemc** [attm2x/m2x-ruby#4]
https://github.com/attm2x/m2x-ruby/blob/master/lib/m2x/stream.rb#L80

Here, `Stream#update_value` uses `:at` for timestamps (from v1), but field name (for v2) should be `:timestamp`.

**Comment by fsaravia** [comment]
@jemc nice catch! Fixed on e662aba611a71af1d513c7a3afd19e1bcb25f8a2
